version: '3.8'

x-logging-template: &logging-template
  driver: "json-file"
  options:
    max-size: "200m"
    max-file: "30"


services:
  haproxy:
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      MQTT_PORT: 1883
      EDGES_RPC_PORT: 7070
      WEBREPORT_PORT: 8383
      FORCE_HTTPS_REDIRECT: "false"

    ports:
     - 0.0.0.0:80:80
     - 0.0.0.0:443:443
     - 0.0.0.0:1883:1883
     - 0.0.0.0:7070:7070
     - 0.0.0.0:9999:9999


  tb-core:
    logging:
      <<: *logging-template

  tb-rule-engine:
    logging:
      <<: *logging-template


  grafana:
    environment:
      GF_SECURITY_ADMIN_PASSWORD: foobar
      GF_USERS_ALLOW_SIGN_UP: 'false'
    user: "472"
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
      # - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/

  prometheus:
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
